services:
  

  app:
    build: ./app
    container_name:  web_app
    ports:
      - "5000:5000"
    depends_on:
      -  db
    environment:
      DATABASE_URL : "postgresql://user:password@db:5432//demo"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: demo
    volumes:
      - db_data:/var/lib/postgresql/data 

  adminer:
    image: adminer:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
  
  proxy:
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - app 

volumes:
  db_data: